---
title: "SURE 2023 - Football/Soccer"
output: html_document
date: "2023-06-21"
---
```{r, warning=FALSE}
# install necessary packages
library(devtools)
library(StatsBombR)
library(worldfootballR)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(FNN)
library(tidymodels)
library(aod)
library(nnet)
library(ranger)
library(readr)
library(mgcv)
library(nlme)
library(yardstick)
library(scoring)
library(ggimage)
library(readr)
```

```{r}
#fotmob matches data
Comp <- FreeCompetitions()
Matches <- FreeMatches(Comp)
fotmob_matches <- fotmob_get_matches_by_date(date = c("20210925"))
fotmob_matches <- c(3609994, 3610132)
match_info <- fotmob_get_match_info(fotmob_matches)
match_details_first <- fotmob_get_match_details(c(3609981))
```

```{r}
#betting and footystat data
bettingPL2018 <- read.csv("E0 (1).csv")
basicInfoPL2018 <- read.csv("england-premier-league-matches-2018-to-2019-stats.csv")
team_data <- read.csv("teams.csv")
team_data_2 <- read.csv("teams2.csv")
players_data <- read.csv("players.csv")

# FIFA Data
FIFA_players <- read.csv("players_18.csv")
Fifa19 <- read_csv("players_19.csv")

PL17_18 <- read_csv("england-premier-league-teams-2017-to-2018-stats (2).csv")
```


```{r}
#match team names
bettingPL2018$HomeTeam <- 
  stri_replace_all_regex(bettingPL2018$HomeTeam,
                         pattern = c("Man United", "Bournemouth",
                                     "Huddersfield", "Newcastle",
                                     "Wolves", "Cardiff", "Leicester",
                                     "Tottenham", "West Ham", "Brighton",
                                     "Man City"),
                         replacement = c("Manchester United", 
                                         "AFC Bournemouth", 
                                         "Huddersfield Town",
                                         "Newcastle United",
                                         "Wolverhampton Wanderers",
                                         "Cardiff City", 
                                         "Leicester City", 
                                         "Tottenham Hotspur",
                                         "West Ham United", 
                                         "Brighton & Hove Albion",
                                         "Manchester City"),
                         vectorize = FALSE)

bettingPL2018$AwayTeam <- 
  stri_replace_all_regex(bettingPL2018$AwayTeam,
                         pattern = c("Man United", "Bournemouth",
                                     "Huddersfield", "Newcastle",
                                     "Wolves", "Cardiff", "Leicester",
                                     "Tottenham", "West Ham", "Brighton",
                                     "Man City"),
                         replacement = c("Manchester United", 
                                         "AFC Bournemouth", 
                                         "Huddersfield Town",
                                         "Newcastle United",
                                         "Wolverhampton Wanderers",
                                         "Cardiff City", 
                                         "Leicester City", 
                                         "Tottenham Hotspur",
                                         "West Ham United", 
                                         "Brighton & Hove Albion",
                                         "Manchester City"),
                         vectorize = FALSE)
```


```{r, warning= FALSE}
#create new variable to match with and merge
bettingPL2018 <- bettingPL2018 %>% 
  mutate(Info = paste(HomeTeam, " ", AwayTeam, "-", Date))

basicInfoPL2018 <- basicInfoPL2018 %>% mutate(datetime = as_datetime(timestamp),
                           date = as_date(datetime),
                           day = day(date),
                           month = month(date),
                           year = year(date),
                           dmy = str_c(day, month, year, sep = "/"),
                           date = format(date, "%d/%m/%Y"))


basicInfoPL2018 <- basicInfoPL2018 %>%
  mutate(Date = make_date(date_GMT),
         Info = paste(home_team_name, " ", away_team_name, "-", date))

bettingBasicPL2018 <- left_join(bettingPL2018, basicInfoPL2018, 
                                       by = "Info")

```


```{r}
#Rename
bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  rename(Home_goals = FTHG, Away_goals = FTAG, Halftime_home_goals = HTHG, 
         Halftime_away_goals = HTAG, Home_shots = HS, Away_shots = AS, 
         Home_shots_on_target = HST, Away_shots_on_target = AST ,Home_fouls = HF, 
         Home_cards =  HC,Away_cards = AC, Home_yellows = HY, Away_yellows = AY , 
         Home_reds = HR, Away_reds = AR, Full_time_result = FTR, Half_time_result = HTR)
```


```{r}
# create new expected win variable
bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  mutate(expect_win = ifelse(((odds_ft_home_team_win < odds_ft_draw) & (odds_ft_home_team_win < odds_ft_away_team_win)), "expected home wins", 
                        ifelse((odds_ft_draw < odds_ft_home_team_win) & (odds_ft_draw < odds_ft_away_team_win), "expected draw", "expected away win")))
```

```{r}
#mosaic plot to compare expected and actual win rate
mosaicplot(table(bettingBasicPL2018$Full_time_result, bettingBasicPL2018$expect_win),
shade = TRUE, main = "Relationship between expected win and actual win?")
```

```{r}
# bar graph for referral
bettingBasicPL2018 %>%
  ggplot(aes(x = Full_time_result, fill = expect_win)) +
  geom_bar() + theme_bw()
```

```{r}
bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  mutate(result = ifelse((Full_time_result == "H") , 0, 
                        ifelse((Full_time_result == "A") , 2, 1)))
set.seed(50) 
train_ids <- sample(1:nrow(bettingBasicPL2018),                    
                                 ceiling(0.75 * nrow(bettingBasicPL2018)))
train_pl <- bettingBasicPL2018[train_ids, ] 
test_pl <- bettingBasicPL2018[-train_ids, ]
# separate predictors and response, again 
train_x <- dplyr::select(train_pl, Home_shots, home_team_possession, home_ppg) 
train_y <- train_pl$result 
test_x <- dplyr::select(test_pl, Home_shots, home_team_possession, home_ppg) 
test_y <- test_pl$result
```

```{r}
#errs_train <- rep(0, 12) 
#errs_test <- rep(0, 12) 
#k_vals <- 1:12 
#for(k in k_vals) {  
 # train_preds <- knn(train = train_x, test = train_x, cl = train_y, k = k, algorithm = "brute") 
 # errs_train[k] <- mean(!train_y == train_preds)  
  #test_preds <- knn(train = train_x, test = test_x, cl = train_y, k = k, algorithm = "brute")  
 # errs_test[k] <- mean(!test_y == test_preds)
#}
```


```{r}
# errors <- bind_cols(train_err = errs_train,                  
#                     test_err = errs_test,                   
#                     k = k_vals)
# errors %>%   pivot_longer(c(train_err, test_err),               
#                           names_to = "err_type") %>%   
#   ggplot(aes(x = k, y = value,             
#              color = err_type)) + 
#   geom_point() +  
#   geom_line() +  
#   labs(y = "Misclassification Rate",       
#        color = "Type of error") + 
#   theme_bw()
```

```{r}
# knn_reg_mod <- nearest_neighbor(
#   mode = "classification",
#   engine = "kknn",
#   neighbors = 5,
#   weight_func = NULL,
#   dist_power = NULL
# )

#result_knn <- knn_reg_mod %>% 
 # fit(result ~ Home_shots + home_ppg + home_team_possession, data= bettingBasicPL2018)

#result_knn
```

```{r}
#possesion vs shots scatterplot
ggplot(bettingBasicPL2018) +
  geom_point(aes(x = Home_shots,
                 y= home_team_possession,
                 color = as.factor(result)
            ),
            size = 2) +
  theme_bw()

```


```{r}
  #firstlm <- glm(as.factor(Full_time_result) ~ Home_shots + home_ppg + home_team_possession, family = "poisson", data= bettingBasicPL2018)
```


```{r}
#converting betting odds to percentages
bettingBasicPL2018 <-  bettingBasicPL2018 %>% 
  mutate(expect_bet_H = 1/B365H,
         expect_bet_A = 1/B365A,
         expect_bet_D = 1/B365D,
         marginal_prob_total = expect_bet_H + expect_bet_D + expect_bet_A,
         percent_H = expect_bet_H *100/marginal_prob_total,
         percent_D = expect_bet_D *100/marginal_prob_total,
         expect_point_H = percent_H * 3 + percent_D,
         Full_time_result_point =  ifelse((Full_time_result == "H"), 3, 
                        ifelse((Full_time_result == "D"), 1, 0)))
  

```



```{r}
#violin plot expected points
bettingBasicPL2018 %>% 
  ggplot(aes(x = Full_time_result,
             y = expect_point_H)) +
  geom_violin() +
  geom_boxplot(width = .2) +
  theme_bw()
  
```


```{r}
#HISTOGRAM OF DIFFERENT RESULTS
bettingBasicPL2018 %>% 
  ggplot(aes(
             x = expect_point_H)) +
  geom_histogram(alpha = .25, position = "identity") +
  facet_wrap(~ Full_time_result, nrow = 3)
```



```{r}
#line-up for Jan 19, 2019 match of Arsenal-Chelsea
Ars_Che_2019Jan <- players_data %>% 
  filter(season == "2018/2019", Current.Club %in% c("Arsenal", "Chelsea")) %>% 
  mutate(starter_Jan19 = (ifelse(full_name %in% c("Kepa Arrizabalaga",	"David Luiz",	"Cesar Azpilicueta",	"Marcos Alonso", "Antonio Rüdiger", "Mateo Kovačić", "Jorginho", "N'Golo Kanté", "Willian", "Eden Hazard",	"Pedro Rodriguez", "Bernd Leno", "Sokratis Papastathopoulos",	"Laurent Koscielny",	"Sead Kolašinac",	"Hector Bellerin", "Aaron Ramsey", "Granit Xhaka", "Lucas Torreira", 	"Matteo Guendouzi",	"Pierre-Emerick Aubameyang",	"Alexandre Lacazette"), "Starter", "Other")))

Ars_Che_2019Jan

```

```{r}
ArsChelFifa <- Fifa19 %>% 
  filter(club_name %in% c("Arsenal", "Chelsea"))
```

```{r}
#matching names
ArsChelFifa$short_name <- 
  stri_replace_all_regex(ArsChelFifa$short_name,
                         pattern = c("E. Hazard", "Kepa",
                                     "N. Kanté", "A. Ramsey",
                                     "B. Leno", "A. Lacazette", "Cesc Fàbregas",
                                     "Sokratis", "A. Iwobi", "A. Morata", "Azpilicueta", 
                                     "M. Kovačić", "G. Cahill", "A. Maitland-Niles", "G. Xhaka", "Héctor Bellerín", "S. Kolašinac", "L. Torreira", "P. Aubameyang", "M. Guendouzi", "L. Koscielny", "Pedro", "A. Rüdiger",
                                     "J. Willock"),
                         replacement = c("Eden Hazard", 
                                         "Kepa Arrizabalaga", 
                                         "N'Golo Kanté",
                                         "Aaron Ramsey",
                                         "Bernd Leno",
                                         "Alexandre Lacazette", 
                                         "Cesc Fabregas", 
                                         "Sokratis Papastathopoulos",
                                         "Alex Iwobi", 
                                         "Alvaro Morata",
                                         "Cesar Azpilicueta",
                                         "Mateo Kovačić",
                                         "Gary Cahill",
                                         "Aisley Maitland-Niles",
                                         "Granit Xhaka",
                                         "Hector Bellerin",
                                         "Sead Kolašinac",
                                         "Lucas Torreira","Pierre-Emerick Aubameyang", "Matteo Guendouzi", "Laurent Koscielny", "Pedro Rodriguez",  "Antonio Rüdiger", "Joe Willock"),
                         vectorize = FALSE)
```

```{r}
#renaming 
ArsChelFifa <- rename(ArsChelFifa, full_name = short_name)
```


```{r}
Ars_Che_2019Jan <- Ars_Che_2019Jan %>% 
  filter(starter_Jan19 == "Starter")
```

```{r}
ArsChelFifa <- ArsChelFifa %>%  
  filter(full_name %in% c("Kepa Arrizabalaga",	"David Luiz",	"Cesar Azpilicueta",	"Marcos Alonso", "Antonio Rüdiger", "Mateo Kovačić", "Jorginho", "N'Golo Kanté", "Willian", "Eden Hazard",	"Pedro Rodriguez", "Bernd Leno", "Sokratis Papastathopoulos",	"Laurent Koscielny",	"Sead Kolašinac",	"Hector Bellerin", "Aaron Ramsey", "Granit Xhaka", "Lucas Torreira", 	"Matteo Guendouzi",	"Pierre-Emerick Aubameyang",	"Alexandre Lacazette"))
```

```{r}
#merging the fifa data
ArsenalChelsea <- left_join(ArsChelFifa, Ars_Che_2019Jan, 
                            by = "full_name")
```

```{r}
#player avg 
chelsea_players <- ArsenalChelsea %>% 
  filter(club_name == "Chelsea") %>% 
  summarise(player_avg = mean(overall))

arsenal_players <- ArsenalChelsea %>% 
  filter(club_name == "Arsenal") %>% 
  summarise(player_avg = mean(overall))
```

```{r}
PL17_18$common_name <- 
  stri_replace_all_regex(PL17_18$common_name,
                         pattern = c("Manchester United", "Bournemouth",
                                     "Huddersfield", "Newcastle United",
                                     "Wolves", "Cardiff", "Leicester City",
                                     "Tottenham Hotspur", "West Ham United", "Brighton & Hove Albion",
                                     "Manchester City", "Stoke City", "West Bromwich Albion", "AFC Bournemouth","Swansea City"),
                         replacement = c("Man United", 
                                         "AFC Bournemouth", 
                                         "Huddersfield Town",
                                         "Newcastle",
                                         "Wolverhampton Wanderers",
                                         "Cardiff City", 
                                         "Leicester", 
                                         "Tottenham",
                                         "West Ham", 
                                         "Brighton",
                                         "Man City", "Stoke", "West Brom", "Bournemouth", "Swansea"),
                         vectorize = FALSE)
```


```{r}
PL17_18 <- PL17_18 %>%  
  filter(team_name %in% c("Man United", "AFC Bournemouth", 
                                         "Newcastle",
                                         "Cardiff City", 
                                         "Leicester", 
                                         "Tottenham",
                                         "West Ham", 
                                         "Brighton",
                                         "Man City", "Stoke", "West Brom", "Bournemouth", "Swansea", "Arsenal", "Liverpool", "Chelsea"))
```


```{r warning = TRUE}
PL17_18 <- rename(PL17_18, Team = common_name)
crests <- read_csv("https://raw.githubusercontent.com/dm13450/FootballCrests/main/crest.csv")
PL17_18 <- left_join(PL17_18, crests, by="Team")

URL <- PL17_18$URL

ggplot(PL17_18, 
  aes(x=points_per_game_home, y=points_per_game_away, label=team_name)) + 
  geom_vline(xintercept = 0) + 
  geom_hline(yintercept = 0) +
  xlab("Pre Match Spread") + 
  ylab("Post Match Spread") + 
  geom_image(aes(image=URL))

```

```{r}
Fifa19 <- Fifa19 %>% 
  filter(league_name == "English Premier League") 
```


```{r}
Fifa19[c("Primary_position", "Secondary")] <- str_split_fixed(Fifa19$player_positions, ',',2)

Fifa19$Primary_position
```

```{r}
Fifa19 <- Fifa19 %>% 
  mutate(Primary_position = case_when(
    (Primary_position %in% c("LW","RW", "ST", "CF") ~ "Forward"),
     (Primary_position %in% c("LM","RM", "CM", "CAM", "CDM") ~ "Midfielder"),
     (Primary_position %in% c("LB","RB", "CB", "RWB", "LWB") ~ "Defender"),
    TRUE ~ "Goalkeeper"
  ))
Fifa19$Primary_position
```

```{r}
players_data$birthday_GMT <- format(as.Date(players_data$birthday_GMT), "%d/%m/%Y")
Fifa19$dob <-format(as.Date(Fifa19$dob,format="%d/%m/%Y"),"%d/%m/%Y")
players_data$dob <- players_data$birthday_GMT
players_data$club_name <- players_data$Current.Club
Fifa19[Fifa19== "Bournemouth"] <- "AFC Bournemouth"
test <-merge(players_data,Fifa19,by=c("club_name","dob"))

```

```{r}
# #
# mins_keans <- 
#   kmeans(dplyr::select(test, min_per_match, overall),
#          algorithm = "Lloyd", centers = 4,
#          nstart = 1)
# 
# test  %>% 
#   mutate(minclusters =
#            as.factor(mins_keans$cluster)) %>% 
#   ggplot(aes(x = min_per_match, y = overall, color = minclusters )) +
#   geom_point() +
#   theme_bw()
```


```{r}
#function to compute streak
streak <- function(df, home, away, index){
  streak_data <- df[1:(index-1),] %>% 
    filter((HomeTeam %in% c(home, away) | AwayTeam %in% c(home, away)))

  n_rows <- nrow(streak_data)
  streak_data <- streak_data[max(1,n_rows-9):n_rows,]
  streak_data <- streak_data %>% 
 
    mutate(
    opposing_team = ifelse(HomeTeam %in% c(home, away), AwayTeam, HomeTeam),
    team = ifelse(HomeTeam %in% c(home, away), HomeTeam, AwayTeam),
    weighted_points = case_when(
      opposing_team %in% c("Liverpool", "Manchester City", "Manchester United", 
                           "Tottenham Hotspur", "Liverpool") ~ 1.5,
      opposing_team %in% c("Arsenal", "Burnley", "Leicester City", "Newcastle United", 
                           "Everton") ~ 1.25,
      opposing_team %in% c("Westham United", "Crystal Palace", "Brighton & Hove Albion", 
                           "AFC Bournemouth", "Watford") ~ 0.75,
      TRUE ~ 0.5),
    Home_away = ifelse(HomeTeam %in% c(home, away), "H", "A"),
    win = case_when(((Home_away == "H" & Full_time_result == "H") | 
                       (Home_away == "A" & Full_time_result == "A")) ~ 1,
                    (Full_time_result == "D") ~ 0, TRUE ~ (-1)))
  
  home_streak <- streak_data %>% 
    filter(team == home) %>% 
    mutate(weighted_streak = weighted_points * win) %>% 
    summarize(streak = sum(weighted_streak))
 
  away_streak <- streak_data %>% 
    filter(team == away) %>% 
    mutate(weighted_streak = weighted_points * win) %>% 
    summarize(streak = sum(weighted_streak))
 
  streak <- paste(c(home_streak, away_streak))
 
  return(streak)
}
```
 

```{r}
#compute on one instance
streak_score <- streak(bettingBasicPL2018, "Arsenal", "Chelsea", 221)

#apply to df
bettingBasicPL2018 <- bettingBasicPL2018 %>% mutate(streak_h = NA, streak_a = NA)
for(i in 1:nrow(bettingBasicPL2018)) {
  streak_score <- streak(bettingBasicPL2018, bettingBasicPL2018$HomeTeam[i],
                         bettingBasicPL2018$AwayTeam[i], i)

  bettingBasicPL2018$streak_h[i] <- streak_score[1]
  bettingBasicPL2018$streak_a[i] <- streak_score[2]
} 
```
 

```{r}
#compute streak diff
bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  mutate(streak_diff = as.integer(streak_h) - as.integer(streak_a))

#expected goals
bettingBasicPL2018 <- bettingBasicPL2018 %>%
  mutate(xg_diff = Home.Team.Pre.Match.xG - Away.Team.Pre.Match.xG)
```
 
```{r}
bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  mutate(Full_time_result_num = case_when(Full_time_result_point == 3 ~ 2, .default = Full_time_result_point))

#set-up training data
train_data_PL <- bettingBasicPL2018 %>% 
  filter(!month %in% 2:5)

test_data_PL <- bettingBasicPL2018 %>% 
  filter(month %in% 2:5)

 
head(bettingBasicPL2018$Full_time_result_num) 
#set-up models
init_logit_gam <- gam(list(Full_time_result_num ~ s(expect_point_H) + s(streak_diff), 
                           ~s(expect_point_H) + s(streak_diff)),
                      data = filter(train_data_PL),
                      family = multinom(K = 2))
 
init_logit_base_gam <- gam(list(Full_time_result_num ~ s(expect_point_H), ~s(expect_point_H)),
                           family = multinom(K = 2), 
                           data = train_data_PL)
```
 
```{r}
#check for summary
summary(init_logit_gam)
summary(init_logit_base_gam)
```
 
```{r}
gam.check(init_logit_gam)
```

```{r}
gam.check(init_logit_base_gam)
```
 

```{r}
init_logit_gam_xg <- gam(list(Full_time_result_num ~ s(expect_point_H) + s(streak_diff) 
                              + s(xg_diff), ~s(expect_point_H) + s(streak_diff) 
                              + s(xg_diff)),
                      data = train_data_PL,
                      family = multinom(K = 2))

summary(init_logit_gam_xg)
```


```{r}
#weighted ranking
test$weightedminutes <- test$min_per_match / 90

test$weighted_overall_rating <- test$weightedminutes * test$over
```
 
```{r}
#grouping by position and average weighted ranking
teams <- test %>% 
  group_by(club_name, position) %>% 
  summarise(position_average = mean(weighted_overall_rating)) %>% 
  select(club_name, position, position_average) %>% 
  ungroup() %>% 
  group_by(club_name) %>% 
  summarise(team_sum = sum(position_average)) 



bettingBasicPL2018 <- bettingBasicPL2018 %>% 
  left_join(teams, by = c("HomeTeam" = "club_name")) %>%
  left_join(teams, by = c("AwayTeam" = "club_name")) %>%  
  mutate(difference_added_avg_pos = team_sum.x - team_sum.y) 

```

```{r}
#brier score dataframe 
brier_score <- data.frame(matrix(nrow = 1))

#multinomial model
expect_model <- nnet::multinom(as.factor(Full_time_result_point) ~ expect_point_H, data = train_data_PL)
summary(expect_model)

predictions <- predict(expect_model, newdata = test_data_PL)

#Predicting the grier score
actual_outcomes <- test_data_PL$Full_time_result_point 
predicted_probs <- predict(expect_model, newdata = test_data_PL, type = "probs")  
cbind(actual_outcomes, predicted_probs)

brier_score['multinomial_base'] = data.frame(
  actual_outcomes,
  predicted_probs
) %>% 
  mutate(actual_outcomes = factor(actual_outcomes)) %>% 
  brier_class(actual_outcomes, X0:X3) %>% 
  select(.estimate)

brier_score <-brier_score[-c(1)] 
row.names(brier_score)[1] <- "brier score"
```


```{r}
predictions <- predict(init_logit_base_gam, newdata = test_data_PL)

#Predicting the grier score
actual_outcomes_gams <- test_data_PL$Full_time_result_point 
predicted_probs_gams <- predict(init_logit_base_gam, newdata = test_data_PL, type = "response")  
cbind(actual_outcomes_gams, predicted_probs_gams)

brier_score['init_logit_base_gam'] = data.frame(
  actual_outcomes_gams,
  predicted_probs_gams
) %>% 
  mutate(actual_outcomes_gams = factor(actual_outcomes_gams)) %>% 
  brier_class(actual_outcomes_gams, X1:X3) %>% 
  select(.estimate)

```

```{r}
predictions <- predict(init_logit_gam, newdata = test_data_PL)

#Predicting the grier score
actual_outcomes_gams <- test_data_PL$Full_time_result_point 
predicted_probs_gams <- predict(init_logit_gam, newdata = test_data_PL, type = "response")  
cbind(actual_outcomes_gams, predicted_probs_gams)

brier_score['init_logit_gam_streak'] = data.frame(
  actual_outcomes_gams,
  predicted_probs_gams
) %>% 
  mutate(actual_outcomes_gams = factor(actual_outcomes_gams)) %>% 
  brier_class(actual_outcomes_gams, X1:X3) %>% 
  select(.estimate)
```

```{r}
predictions <- predict(init_logit_gam_xg, newdata = test_data_PL)

#Predicting the grier score
actual_outcomes_gams <- test_data_PL$Full_time_result_point 
predicted_probs_gams <- predict(init_logit_gam_xg, newdata = test_data_PL, type = "response")  
cbind(actual_outcomes_gams, predicted_probs_gams)

brier_score['init_logit_gam_xg'] = data.frame(
  actual_outcomes_gams,
  predicted_probs_gams
) %>% 
  mutate(actual_outcomes_gams = factor(actual_outcomes_gams)) %>% 
  brier_class(actual_outcomes_gams, X1:X3) %>% 
  select(.estimate)
```

```{r}
#random forest model with brier score
random_forest <- ranger(Full_time_result_num ~ expect_point_H + streak_diff + xg_diff, data = train_data_PL, probability = TRUE)

predictions <- predict(random_forest, data = test_data_PL)

#Predicting the grier score
rf_outcomes <- test_data_PL$Full_time_result_point 
rf_probs <- predict(random_forest, data = test_data_PL, type = "response")  
cbind(rf_outcomes, rf_probs)
  
brier_score['randForest_streak'] = data.frame(
  rf_outcomes,
  rf_probs
) %>% 
  mutate(rf_outcomes = factor(rf_outcomes)) %>% 
  brier_class(rf_outcomes, X1:X3) %>% 
  select(.estimate)
```

```{r}

```

